# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PLEDIN 3.0
email: josedom24@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pledin" # the subpath of your site, e.g. /blog
url: "http://plataforma.josedomingo.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pledin_jd
github_username:  josedom24
paginate: 0

timezone: Europe/Madrid

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

locale: "es-ES"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
name: "José Domingo Muñoz"
search: true
repository: "josedom24/plataforma_pledin"

twitter:
  username: "pledin_jd"

author:
  name   : "José Domingo Muñoz"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Plataforma Educativa Informática"
  email  : "josedom24@gmail.com"
  uri    : "https://www.josedomingo.org"
  github : "josedom24"
  gitlab : "josedom24"
  twitter : "pledin_jd"
  location: "Utrera, Sevilla,ES" # null (default), "absolute or relative url to link to author home"

collections:
  cursos:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: cursos
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      sidebar:
        nav: "cursos"
      
      
